### ISSUE TITLE
Support for Sommerfeld Integrals?

### ISSUE THREAD

**Issue by twhughes** [steven-murray/hankel#48]
**Question:**
I'm interested in using `hankel` to solve problems in numerical electromagnetics involving 'sommerfeld integrals'.  These integrals can be expressed as a radially symmetric fourier transform and solved with `hankel`.  However, there are some extra numerical issues involved when dealing with singularities and branch cuts present in the integrand.

I'm wondering if you have any experience using hankel to solve these types of integrands, if you have an example to show, or if you know of a good reference.  I am new to numerical hankel transformations so any insight is appreciated!

**Additional Context:**

https://en.wikipedia.org/wiki/Sommerfeld_identity

For reference, sommerfeld integrals can be generally expressed in the following form (numpy syntax)

`f(k) = k / np.sqrt(c ** 2 - k ** 2) * scipy.special.j0(k * q) * np.exp(d * np.sqrt(c ** 2 - k ** 2))`

Where `c` and `d` are constants.  This function is integrated from k = 0 to infinity along the real axis.  Therefore, it can be naturally expressed as a radially symmetric fourier transform.  

We see that there is a pole at `k = c`.

**Comment by steven-murray** [comment]
Hi @twhughes and thanks for the question. 

This is interesting. I've certainly never implemented the Sommerfield integral, nor an integrand with a pole. On the face of it, I think `hankel` will struggle with this. One option of course is just to split the integral into two and try some kind of variable transform, though it looks like that might make it no longer a hankel transform. Otherwise, you could try manually defining your function to return zero at the pole instead of NaN or inf. That may be enough?

**Comment by twhughes** [comment]
Thanks, @steven-murray.

No problem, I figured it was a long shot but wanted to ask anyway :).  I have messed around a bit with the integral using `hankel` and came to some results by adding some artificial imaginary part to `c` to avoid the poles.  This seems to allow me to get an approximate answer using the radial fourier transform, but it still requires very high `N` and low `h` in the quadrature used in hankel.

I'll continue playing with it a bit, there is extensive (and quite opaque) literature on the subject I'll probably just have to dive into.

Appreciate your help and glad I found your package!
